---
version: 2

workflows:
  version: 2
  test:
    jobs:
      - otp-23
      - otp-24
      - otp-25

jobs:
  otp-23: &test-template
    docker:
      - image: circleci/erlang:23
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run EUnit
          command: make eunit
      - run:
          name: Run Dialyzer
          command: make dialyze

  otp-24:
    <<: *test-template
    docker:
      - image: circleci/erlang:24

  otp-25:
    <<: *test-template
    docker:
      - image: circleci/erlang:25
